"""empty message

Revision ID: 23a3e3ef42d8
Revises:
Create Date: 2026-09-23 12:29:06.897004

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "23a3e3ef42d8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=63), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "books",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=127), nullable=False),
        sa.Column("year_of_writing", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=31), nullable=False),
        sa.Column("last_name", sa.String(length=31), nullable=False),
        sa.Column("surname", sa.String(length=31), nullable=False),
        sa.Column("phone_number", sa.String(length=10), nullable=False),
        sa.Column("hashed_password", sa.String(length=127), nullable=False),
        sa.Column(
            "events_ok", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "is_admin", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("verification", sa.String(length=23), nullable=False),
        sa.Column("sqlite_region_id", sa.Integer(), nullable=False),
        sa.Column("sqlite_settlement_id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "verification ~ '^(tg_id:[0-9]+|AA|RA|token:[A-Za-z0-9]{6})$'",
            name="verification_check",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "first_name",
            "last_name",
            "surname",
            "phone_number",
            "sqlite_region_id",
            "sqlite_settlement_id",
            name="unique_user",
        ),
    )
    op.create_index(
        "unique_verification_prefixed",
        "users",
        ["verification"],
        unique=True,
        postgresql_where="verification ~ '^(tg_id|token)'",
    )
    op.create_table(
        "authors_books",
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.PrimaryKeyConstraint("author_id", "book_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("authors_books")
    op.drop_index(
        "unique_verification_prefixed",
        table_name="users",
        postgresql_where="verification ~ '^(tg_id|token)'",
    )
    op.drop_table("users")
    op.drop_table("books")
    op.drop_table("authors")
    # ### end Alembic commands ###
