"""Add users model

Revision ID: 8b06039201d0
Revises: 1a03b31ac447
Create Date: 2026-09-15 15:17:34.092338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b06039201d0'
down_revision: Union[str, Sequence[str], None] = '1a03b31ac447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=31), nullable=False),
    sa.Column('last_name', sa.String(length=31), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('hashed_password', sa.String(length=127), nullable=False),
    sa.Column('events_ok', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sqlite_region_id', sa.Integer(), nullable=False),
    sa.Column('sqlite_settlement_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_name', 'last_name', 'phone_number', 'sqlite_region_id', 'sqlite_settlement_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
